import { createSlice } from '@reduxjs/toolkit';

import { fetchMovieAsync} from './thunks';
import { MoviesState } from './types';

const initialState: MoviesState = {
  data: [],
  status: 'idle',
};

export const movieSlice = createSlice({
  name: 'movies',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    resetMovies: (state) => {
        state.data = []
        state.status = 'idle'
      }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchMovieAsync.pending, (state) => {
        state.status = 'pending';
      })
      .addCase(fetchMovieAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.data = action.payload.data;
      })
  },
});

export default movieSlice;